language: python
script: py.test
 
install:
  - sudo apt-get update --fix-missing   
  #- sudo apt-get install -y nasm build-essential python-dev libdwarf-dev libelf-dev
  - sudo pip install requests
